### ISSUE TITLE
Feature: Enable CRUD for manager

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#19] opened 2024-12-02 20:07 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

The manager should be able to do CRUD operations for nodes and jobs

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment] 2024-12-05 22:25
Duplicate of https://github.com/absmach/propeller/issues/25

**Closed by drasko** 2024-12-05 22:25 UTC
