### ISSUE TITLE
Feature: Expose worker stats

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#17] opened 2024-12-02 19:53 UTC
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Expose worker stats such as CPU, memory and disk usage. Also, add the number of running tasks and the total number of tasks running

The worker should expose a liveness or health endpoint where the manager can continuously check that it is alive before assigning it a job

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment] 2024-12-05 22:15
Duplicate of https://github.com/absmach/propeller/issues/10

**Closed by drasko** 2024-12-05 22:15 UTC
